### ISSUE TITLE
Implement permissions.

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/officeportal#24]
@ghermans can u provide me a permission schema

**Comment by ghermans** [comment]
## Permissions

#### Departments
- create-departments
- view-departments
- delete-departments

#### Staff
-  create-user
-  edit-user
-  remove-user

#### News
- manage-news

#### Service Requests
- request-service
- manage-services

#### Tool management
- create-tool
- edit-tool
- delete-tool

## Roles

Name | Permissions
------------ | -------------
Administrator | ALL
Management | ALL
Engineer | request-service, view-departments
Developer | request-service, view-departments
Sales | request-service, view-departments
Support | request-service, view-departments

**Comment by ghermans** [comment]
@Tjoosten if you use `bouncer `for this, please verify that the permissions are assigned when using `db:seed`
